apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    buildFeatures {
        dataBinding true
    }
}

repositories {
    maven {
        url "https://maven.regulaforensics.com/RegulaDocumentReader/Stage"
    }
}

dependencies {
    implementation('com.regula.idv:api:3.9.344') {
        transitive = true
    }
}
